<!DOCTYPE html>
<html lang="vi">
  <head>
      <?php echo $this->headTitle(); ?>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headLink(); ?>
   <?php echo $this->headScript(); ?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ngọc Phương Shop</title>

    <!-- Bootstrap CSS -->
   

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>

    <div class="container">

  <?php include ("includes/header.php"); ?>

      <div id="topmenu" class="row">
        <ul class="nav nav-justified">
          <li class="first active">
            <a href="list.html" class="menu-icon-1"><span>&nbsp;</span>Desktop</a>
          </li>
          <li>
            <a href="list.html" class="menu-icon-2"><span>&nbsp;</span>Laptop</a>
          </li>
          <li>
            <a href="list.html" class="menu-icon-3"><span>&nbsp;</span>Linh kiện PC</a>
          </li>
          <li>
            <a href="list.html" class="menu-icon-4"><span>&nbsp;</span>Phụ kiện PC</a>
          </li>
          <li>
            <a href="list.html" class="menu-icon-5"><span>&nbsp;</span>Thiết bị văn phòng</a>
          </li>
          <li>
            <a href="list.html" class="menu-icon-6"><span>&nbsp;</span>Thiết bị mạng</a>
          </li>
          <li>
            <a href="list.html" class="menu-icon-7"><span>&nbsp;</span>Thiết bị khác</a>
          </li>
        </ul>
      </div>


     <!-- ***************************** Banner slide ************************ -->
  <?php include ("includes/banner-slide.php"); ?>


<!-- content -->
<?php echo $this->layout()->content; ?>






  <!-- jQuery -->
  

  </body>
</html>