      <div class="row">
        <ol class="breadcrumb">
          <li>
            <a href="index.html">Trang chủ</a>
          </li>
          <li>
            <a href="contact.html">Liên hệ</a>
          </li>
          <li class="active">NgocPhuong Shop</li>
        </ol>
      </div>



      <div class="row">

        <div id="contact" class="col-xs-6 col-sm-6 col-md-6 col-lg-6">

          <div class="item">
            <h3>Gửi thông tin liên hệ</h3>
            <p>Thank you for stopping by! We are happy to hear from you. Please contact us through the form below and we will get back to you as soon as we can. </p>

            <div class="fields">
              <label class="required" for="Contact_name">Tên <span class="required">(*)</span></label>
              <input type="text" id="Contact_name" name="Contact[name]" maxlength="255" size="60">
            </div>

            <div class="fields">
              <label class="required" for="Contact_email">Email <span class="required">(*)</span></label>
              <input type="text" id="Contact_email" name="Contact[email]" maxlength="255" size="60">
            </div>

            <div class="fields">
              <label class="required" for="Contact_phone">Điện thoại <span class="required">(*)</span></label>
              <input type="text" id="Contact_phone" name="Contact[phone]" maxlength="255" size="60">
            </div>

            <div class="fields">
              <label class="required" for="Contact_body">Nội dung <span class="required">(*)</span></label>
              <textarea name="Contact[body]" rows="8" cols="40" id="Contact_body"></textarea>
            </div>

            <div class="buttons">
              <input type="submit" value="Gửi đi" class="btn btn-primary btn_g">
            </div>
          </div>

        </div>


        <div id="right-contact" class="col-xs-6 col-sm-6 col-md-6 col-lg-6 text-left">
          <div>
            <a href="<?php echo $this->imgUrl; ?>/map.jpg" target="_blank"><img class="map" src="<?php echo $this->imgUrl; ?>/map.jpg" alt=""></a>
            <img class="bg" src="<?php echo $this->imgUrl; ?>/contact_bg_icon.png" alt="">

            <h3 class="company">Công ty tin học máy tính Ngọc Phương</h3>
            <span><strong>Add:</strong> Số 86 Lạch Tray - Ngô Quyền - Hải Phòng</span><br />
            <span><strong>Tel:</strong> 0935.565.586 - 0935.565.586</span><br />
            <span><strong>Email:</strong> <a href="mailto:info@domainname.com">info@domainname.com</a></span><br />
          </div>

        </div>

      </div>